services:
  - type: web
    name: accident-detection-fastapi
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.4
      - key: CUDA_VISIBLE_DEVICES
        value: "-1"
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "3"
